# Generated by Django 2.2.9 on 2020-04-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ocultar'), (1, 'Publicar')], default=0),
        ),
    ]
