# Generated by Django 2.2.9 on 2020-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20200420_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('referencia', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=8)),
                ('direccion', models.CharField(max_length=128)),
                ('estado', models.IntegerField(choices=[(0, 'ENVIADO'), (1, 'PROCESANDO'), (2, 'ENTREGADO')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('productos', models.ManyToManyField(to='inicio.Producto')),
            ],
        ),
    ]
